build: Check for pkg-config in boostrap
* bootstrap: Likewise.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -20,8 +20,14 @@ test -n "$srcdir" || srcdir=.
 ORIGDIR=`pwd`
 cd $srcdir
 
+PKGCONFIG=`which pkg-config`
+if test -z "$PKGCONFIG"; then
+  echo "*** pkg-config not found, please install it ***"
+  exit 1
+fi
+
 AUTORECONF=`which autoreconf`
-if test -z $AUTORECONF; then
+if test -z "$AUTORECONF"; then
   echo "*** No autoreconf found, please install it ***"
   exit 1
 fi
